### PR TITLE
added domoticz plugin

### PR DESCRIPTION
**Pull request by josefpavlik**
hi
this is a plugin for domoticz https://www.domoticz.com/ , it controls the relays and reads the opto inputs. Currently there is only support for relays and inputs. These devices are seen as light/switch in domoticz.
The directory libioplus is simplified copy of your python library.

best regards
Josef

### CODE REVIEW

**Comment by alexburcea2877** [comment]
Hi,

Thank you for including us in the Domoticz community. I currently have no resource (time)  to cover the subject so I will do the merge without testing it. Thank you again and after find some time to read Domoticz documentation and install I might be able to help .

Alex.

**Comment by alexburcea2877** [comment]
Hi,
I just receive one question:

_"I have 2 HOME AUTOMATION Cards for Raspberry Pi connected to my Pi with Domoticz but I only get 16 inputs and 16 outputs listed at Devices.
How can I use the other functions of your card with Domoticz?"_

Can you help me with that or I should start learning about Domoticz?

**Comment by josefpavlik** [comment]
Sorry, I've found your question only now. You can create more than one device in domoticz, set different ""board number" in the config of two devices.
Every device will have 16 relays and 16 inputs.
I already does not have the raspberry with this board and with domoticz, so I cannot try it.
regards
Jet

**Comment by alexburcea2877** [comment]
Thank you. I forwarded the answer.
Alex.

**Pull request merged**
